---
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  EcsClusterArn:
    Type: AWS::SSM::Parameter::Value<String>
  EcsServiceName:
    Type: AWS::SSM::Parameter::Value<String>
  LogGroupName:
    Type: AWS::SSM::Parameter::Value<String>
  LogRegionName:
    Type: AWS::SSM::Parameter::Value<String>
  LogStreamPrefix:
    Type: AWS::SSM::Parameter::Value<String>
  LogDriverName:
    Type: AWS::SSM::Parameter::Value<String>
  EcrImageTag:
    Type: String    
  EcrImageUri:
    Type: AWS::SSM::Parameter::Value<String>
  EcsTaskDefinitionFamily:
    Type: AWS::SSM::Parameter::Value<String>
  IamRoleArn:
    Type: AWS::SSM::Parameter::Value<String>
  EnvironmentFile:
    Type: String

Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Tags:
        - Key: Service
          Value: actions-runner
      Family: !Ref EcsTaskDefinitionFamily
      TaskRoleArn: !Ref IamRoleArn
      ExecutionRoleArn: !Ref IamRoleArn
      Cpu: 1024
      Memory: 2048
      RequiresCompatibilities:
        - EC2
      NetworkMode: bridge
      ContainerDefinitions:
        - EnvironmentFiles:
            - Type: s3
              Value: !Ref EnvironmentFile
          LogConfiguration:
            LogDriver: !Ref LogDriverName
            Options:
              awslogs-group: !Ref LogGroupName
              awslogs-region: !Ref LogRegionName
              awslogs-stream-prefix: !Ref LogStreamPrefix
          Image: !Sub "${EcrImageUri}:${EcrImageTag}"
          Name: actions-runner
          Privileged: true

  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref EcsClusterArn
      ServiceName: !Ref EcsServiceName
      LaunchType: EC2
      PropagateTags: TASK_DEFINITION
      TaskDefinition: !Ref TaskDefinition
      DeploymentConfiguration:
        MinimumHealthyPercent: 50
        MaximumPercent: 100
